### ISSUE TITLE
Support migration from CentOS to RHEL

### ISSUE THREAD

**Issue by phracek** [upgrades-migrations/redhat-upgrade-tool#10]
I have tried to migrate CentOS 6 to RHEL 6 with redhat-upgrade-tool but it failed with message:
[root@centos66 ~]# redhat-upgrade-tool --network 6.6 --instrepo ..snip.. --force
setting up repos...
cmdline-instrepo                                                                                                                                                       | 4.1 kB     00:00  
optional                                                                                                                                                               | 3.8 kB     00:00  
.treeinfo                                                                                                                                                              | 1.9 kB     00:00  
getting boot images...
.treeinfo                                                                                                                                                              | 1.9 kB     00:00     

Downloading failed: invalid data in .treeinfo: No option 'upgrade' in section: 'images-x86_64'
[root@centos66 ~]#

**Comment by phracek** [comment]
System was installed from http://ftp.cvut.cz/centos/6.6/isos/x86_64/
python-rhsm package does not exist on CentOS and I have commented the import. Also checking for Red Hat Enterprise Linux was forced and it would be good to allow CentOS. 

If I am able to create a pull request then I will do it.

**Comment by bocekm** [comment]
We do not plan to support migrations from CentOS to RHEL using this tool anymore. For CentOS to RHEL migrations options, contact [Red Hat Consulting](https://www.redhat.com/en/services/consulting).
