### ISSUE TITLE
Use import preupg instead of preup

### ISSUE THREAD

**Issue by phracek** [upgrades-migrations/redhat-upgrade-tool#15]
preupgrade assistant did a huge refactoring.
Class is available in preupg instead of preup.

Modify calling of preupgrade assistant API

**Comment by bocekm** [comment]
Fixed in commit https://github.com/upgrades-migrations/redhat-upgrade-tool/commit/49ce1a67fec7833c80d2b3dc9f82de27bc7e6dae, released in v0.7.48.
