### ISSUE TITLE
Support for assessment format version: stage 3 (r-u-t)

### ISSUE THREAD

**Issue by AloisMahdal** [upgrades-migrations/redhat-upgrade-tool#31]
This is part of a greater change that needs to be done in all three codebases in 3 stages:

  * [ ] 1. preupgrade-assistant-modules ([#31][s1]),
  * [ ] 2. preupgrade-assistant ([#335][s2]),
  * [ ] 3. **redhat-upgrade-tool** (this ticket).

  [s1]: https://github.com/upgrades-migrations/preupgrade-assistant-modules/issues/31
  [s2]: https://github.com/upgrades-migrations/preupgrade-assistant/issues/335

Below is the complete description:

---

Assessment, as a data object does not currently have any concept of versioning.  Any tools that further work with it (redhat-upgrade-tool, preupg-kickstart-creator, preupg UI...) simply have to assume that they "understand" the data.

The solution is to introduce assessment format version.   The flow is:

 *  Module set declares its abability to produce assessment in version $V.  This can be done
    by means of key/value pair in properties.ini

        assessment_format_version = 0.1

 *  Assisstant launches modules and passes this information as part of assessment
    somewhere under (/root/preupgrade as well as in tarball).

 *  *redhat-upgrade-tool* hardcodes range of versions (actually just one particular version)
    it's able to "understand" and compares this against assessment version.  If the versions
    match, it can continue.  If the versions don't match or assessment version cannot be
    determined, it advises user to install respective module set and re-run assessment.

**Comment by pirat89** [comment]
The issue is obsoleted for a long time.
