### ISSUE TITLE
Upgrade from 6.9 to 7.4 fails 

### ISSUE THREAD

**Issue by cdevoe57** [upgrades-migrations/redhat-upgrade-tool#37]
I use the term upgrade for the major version and update for the minor version.

I am trying to upgrade from 6.9 to 7.4.  We have set up a local repository to do the latest  update of 6.9

I copy the 7.4 install DVD (all 4.8GB) to the server and do the upgrade from there

redhat-upgrade-tool-cli --iso /home/user/linux7_4.iso

If I do the update from the local repository the upgrade fails.  When I do the update from the public repositories the upgrade works.    It seems to have some sort of issue finding the packages.  I've been fighting this for about 3 weeks and could use some new ideas.....

![image](https://user-images.githubusercontent.com/30262564/36682280-b315662a-1ae8-11e8-8569-fc40cb76a2cc.png)

**Comment by timizod** [comment]
The process I'm testing for upgrading from 6.8 to 7.4 is roughly:

```
yum -y install preupgrade-assistant preupgrade-assistant-el6toel7 redhat-upgrade-tool

echo Y | preupg -v

mv /etc/yum.repos.d/* /root/ # avoid clashes with pre-existing repos

redhat-upgrade-tool -v --cleanup-post  --network 7.4 --instrepo http://repos/isos/rhel-server-7.4-x86_64/

reboot
```

The 7.4 repo in our environment is a copy of the 7.4 iso. We haven't tried using a copy of the ISO image locally on a machine.

**Comment by pirat89** [comment]
@cdevoe57 I havn't use the --iso as the source for a while, but have you tried to store iso into the root partition? (in case that home is not on the root partition). Just curious whether it could be the reason of the issue or not. From the screen I don't know whether iso has been mounted succesfully or not.

**Comment by mfranczy** [comment]
@cdevoe57 instead of sending screenshot can you send us full log from execution?

**Comment by mfranczy** [comment]
I checked local repo setup and it works fine, due to that fact I am closing this issue.
If someone would disagree with this, then with reopening issue please attach logs.
