### ISSUE TITLE
Additional repositories are not processed

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/redhat-upgrade-tool#38]
It seems that repositories added by the `--addrepo` option are not used during the calculation of the transaction because of *productid*. Maybe it's connected to some checks that are made for instrepo, but are not necessary (IMO) for additional repositories. In addition, the messages are printed after the rpms are downloaded, which looks weird too. I would expect such info before the rpm transaction is finished. But I don't see into the logic of the tool so deep.

```
redhat_upgrade_tool.yum WARNING: Error loading productid metadata for rhel-7-opt.
redhat_upgrade_tool.yum WARNING: Error loading productid metadata for rhsedmrhelup.
```

**Comment by mfranczy** [comment]
@pirat89 what do you mean by 

>  because of productid

is it invalid or what? I am trying to understand that problem..

**Comment by pirat89** [comment]
@mfranczy I dunno. As I wrote:
> It seems that
So not sure what exactly is wrong (see the warning msgs). In my case the repo has been "loaded" but I havn't seen used any rpm  from the repository during the in-place upgrade even when I expected at least few rpms used.

Another thing is the warning msg. It needs to be investigated what exactly is wrong. It is weird that we have report where you can see it is working correctly (still with the warning msg) and another two people found it doesn't. I will try to reproduce it with particular rpms & repos.

**Comment by pirat89** [comment]
It's weird. Now the RPMs from the added repository are downloaded. Even in the code (below) it is written the repository should be skipped as I see now, but the RPMs are downloaded and copied into the `/system-upgrade` directory so it is prepared to be updated.

https://github.com/upgrades-migrations/redhat-upgrade-tool/blob/448678db22401c3f76d279548d56a3423d51265a/redhat_upgrade_tool/download.py#L350

**Comment by mfranczy** [comment]
Repo shouldn't be skipped at this stage, only certs and it works like that, so i think this is correct.
