### ISSUE TITLE
redhat-upgrade-tool --clean throws a traceback

### ISSUE THREAD

**Issue by pkotvan** [upgrades-migrations/redhat-upgrade-tool#44]
This issue is related to pull request #42.
Setup: RHEL-6.10 / x86_64 / Server / Minimal package set

Upgrade:
redhat-upgrade-tool --network 7.5 --instrepo \<URL\> --snapshot-root-lv vg_rhel600/LogVol01

The upgrade was successful. After the upgrade I booted to RHEL-7 and tried to execute:
redhat-upgrade-tool --clean

The command failed with the follwoing traceback:

```
# redhat-upgrade-tool --clean
Traceback (most recent call last):
  File "/bin/redhat-upgrade-tool", line 346, in <module>
    main(args)
  File "/bin/redhat-upgrade-tool", line 117, in main
    do_cleanup(args)
  File "/usr/lib/python2.7/site-packages/redhat_upgrade_tool/commandline.py", line 232, in do_cleanup
    for cert in filvgs
t-lv vg_rhel600/LogVol01kkl/released/RHEL-7/7.5/Server/x86_64/os/ --snapshot-root
```

**Comment by pirat89** [comment]
This is error of rhelup in master branch which we do not plan to fix as only rhelup that has some development is in the rhel-6 branch.
